### ISSUE TITLE
Feature: Add Simple Google Search

### ISSUE THREAD

**Issue by Jeffrey-R** [bdrathburn/TeslaForumPersonalBlocklist#4]
Replace complicated Google Search w/ simple form w/ Advanced Search Options:

as_q => Query String to search for
as_sitesearch => Site to constrain search to (tesla.com/forum/forums)

**Comment by Jeffrey-R** [comment]
Here is my first draft:

```
(function (){
// added JeffreyR v.1.0.3
// closure function to add simple Google Search
    var Google_Search   = document.createElement('div');
    var gs  =   '<form accept-charset="utf-8" target="_search" action="https://www.google.com/search">';
        gs  +=  '<input name="as_sitesearch" type="hidden" value="tesla.com/forum/forums">';
        gs  +=  '<input name="as_q" type="text" value="" placeholder="Enter text to find" style="width: auto; margin-top: 0.2em; margin-bottom: 0.3em; margin-left: 2px;">';
        gs  +=  '<input type="submit" value="Search" class="btn-primary" title="Google Custom Site Search for tesla.com Forums">';
        gs  +=  '</form>';

    Google_Search.innerHTML = gs;

    var OP_Right    = document.getElementsByClassName('right-column panel-panel sidebar')[0];
    if(OP_Right != null) { 
        OP_Right.firstElementChild.appendChild(Google_Search);
    }

    var Posts_Right = document.getElementById('second-header');
    if(Posts_Right != null) {
        if(Posts_Right.firstElementChild.firstElementChild.className == "grid-6") {
            Google_Search.style.width   = "300px;";
            Google_Search.style.float   = "right";
            Posts_Right.firstElementChild.firstElementChild.appendChild(Google_Search);
        }
    }

})();
```

The form is the same as my example search.html, but I am re-using Tesla's CSS except for search field width and white-space.

Posts:
![image](https://cloud.githubusercontent.com/assets/21967372/18425707/63a4ffde-7881-11e6-803b-4b7a7627cc17.png)

![image](https://cloud.githubusercontent.com/assets/21967372/18425713/7694ac16-7881-11e6-94b8-8e8f42f8eac0.png)

Threads:
![image](https://cloud.githubusercontent.com/assets/21967372/18425721/8ef2d9c2-7881-11e6-8be7-1d92fa2b6ba9.png)

(if too narrow they go away)
![image](https://cloud.githubusercontent.com/assets/21967372/18425735/a41e92fa-7881-11e6-8ed9-a6af05e954ff.png)

**Comment by Jeffrey-R** [comment]
I'll see if I can make them more like the Posts section....

**Comment by Jeffrey-R** [comment]
Here's a version that does not disappear:

```
(function (){
// added JeffreyR v.1.0.3
// closure function to add simple Google Search
    var Google_Search   = document.createElement('div');
    var gs  =   '<form accept-charset="utf-8" target="_search" action="https://www.google.com/search">';
        gs  +=  '<input name="as_sitesearch" type="hidden" value="tesla.com/forum/forums">';
        gs  +=  '<input name="as_q" type="text" value="" placeholder="Enter text to find" style="width: auto; margin-top: 0.2em; margin-bottom: 0.3em; margin-left: 2px;">';
        gs  +=  '<input type="submit" value="Search" class="btn-primary" title="Google Custom Site Search for tesla.com Forums">';
        gs  +=  '</form>';

    Google_Search.innerHTML = gs;
    Google_Search.style.float   = "right";

    var OP_Right = document.getElementById('second_header');
    if(OP_Right != null) { 
        OP_Right.firstElementChild.appendChild(Google_Search);
    }

    var Posts_Right = document.getElementById('second-header');
    if(Posts_Right != null) {
        if(Posts_Right.firstElementChild.firstElementChild.className == "grid-6") {
            Google_Search.style.width   = "300px;";
            Posts_Right.firstElementChild.firstElementChild.appendChild(Google_Search);
        }
    }
})();
```

Posts:
![image](https://cloud.githubusercontent.com/assets/21967372/18426180/27e5db04-7885-11e6-9778-eb6abcf6fbe2.png)

![image](https://cloud.githubusercontent.com/assets/21967372/18426188/35f45e50-7885-11e6-94e0-c43655a2c0ea.png)

Threads:
![image](https://cloud.githubusercontent.com/assets/21967372/18426199/4990b440-7885-11e6-9da2-bab27dfdd831.png)

![image](https://cloud.githubusercontent.com/assets/21967372/18426204/56651346-7885-11e6-9c9c-7d333678ac31.png)

I tried using the "system_messages" DIV (area showing View|Edit) but it gets covered by the post title. That may be our best bet if we can figure out how to keep it on top.

**Comment by bdrathburn** [comment]
Added to V 1.0.3 and published. It works well enough to incorporate for now, we can always polish it up later if needed. Thanks.
